### ISSUE TITLE
Support .net standard 2.0

### ISSUE THREAD

**Issue by mcatanzariti** [SaviorXTanren/mixer-client-csharp#13]
By supporting .Net standard 2.0, mixer-client-csharp could be used in a ASP.Net Core web application

**Comment by SaviorXTanren** [comment]
Just performed the conversion and pushed it to the branch "standard2Conversion". So far, everything "seems" to be working fine. Going to experiment a bit with a few sample apps and projects I have to make sure things are still working. I'm still undecided about whether this is the right thing to do, since there is a dependency on VS2015 for use and VS2017 for development. As it stands now, I'm more tempted to delay this until after 2017 has had a bit more adoption.

**Comment by SaviorXTanren** [comment]
Re-opening this issue and subsequently closing this to re-notify of updates. I just pushed up to master the official changes to convert this over to the .NET Standard 2.0, so it should be all good to go. The updated NuGet package has also been published.
