### ISSUE TITLE
Websocket closes connection

### ISSUE THREAD

**Issue by D3thw0lf** [SaviorXTanren/mixer-client-csharp#14]
At some Point the websocket is closing the connection for no reason. The "onDisconnected" Event isn't casting if this is happening and Client is crashing for losing connection.

```
2017-10-08 15:41:33.3036 FATAL System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state for this Operation ('Aborted'). Gültige Zustände sind: 'Open, CloseReceived'
   bei System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState state, WebSocketState[] validStates)
   bei System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Mixer.Base.Clients.WebSocketClientBase.<Send>d__31.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Mixer.Base.Clients.WebSocketClientBase.<SendAndListen>d__32.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Mixer.Base.Clients.ChatClient.<ClearMessages>d__50.MoveNext()
```

Just wanted to Report this in case this is not a problem on my side (Network Card etc.).

**Comment by SaviorXTanren** [comment]
The websocket will close itself on occasion if there is a large amount of in-activity or sometimes just due to a random packet drop that throws things off. Unless we receive a packet stating that the connection is being closed, we won't inherently know whether the socket is closed. I removed the auto-re-connection logic for all websocketclients, moving the onus onto the using application to handle it how they want, but I don't think that's the case here based on what you said.

What I can try to do is look into adding a repeated keep-alive ping for each of the clients that can run every so often to hopefully keep the connection open. The other aspect I could look in to is if we detect a closed connection when attempting to send a command, we can re-establish the connection, then send the message. I'll look in to this tonight when I get a chance.

**Comment by D3thw0lf** [comment]
Thank you for the decleration of that issue so I now know that it does not come from my Network Card ^w^

Hope you can find a good solution that fits the needs of this wonderful lib and as always thanks for your hard work on this. :)

**Comment by SaviorXTanren** [comment]
Of course, happy to help :) Just pushed up a change that adds a ping every 30 seconds to all clients and raises the Disconnected event if we fail a ping. Hopefully that should help keep the socket open and alert you if there's issues. Let me know if you still see disconnection and I can decrease the time to something lower.

**Comment by D3thw0lf** [comment]
Your fix nailed it. Seems to stay connected now. Thanks for the fast solution. 👍
