### ISSUE TITLE
OnUserUpdateOccured - Username Not Populated

### ISSUE THREAD

**Issue by xlxAciDxlx** [SaviorXTanren/mixer-client-csharp#22]
When logging inside a handler for the `OnUserUpdateOccured` event, the `username` field of the `ChatUserEventModel` class is not populated.

**Comment by SaviorXTanren** [comment]
So, there's both a bug and not a bug in this.

The bug is that the event doesn't have an "id" field, but instead has a "user" field which contains the user's ID. I made a quick update for this that simply created a wrapper "user" field which assigns and pulls from the ID field to keep simplicity.

The fact that a username is not returned is actually by-design for the Mixer APIs, it will only return what's actually changed about the user. In the case of a user being modded for example, only the roles of the user changed, so only their ID and their new roles set will be returned. If they changed their username, then their name would be included in the packet.

For your bot, I'd suggest simply calling the user's API on the channel to get their new information when this event is returned, as it won't always be consistent with what the event actually "means" when it gets fired.
