### ISSUE TITLE
[Question] MixerConnection.Channels.GetChannel Hangs

### ISSUE THREAD

**Issue by xlxAciDxlx** [SaviorXTanren/mixer-client-csharp#27]
So sorry to keep asking so many questions that I'm sure are caused by me missing something simple or just making a mistake, but is there any way to diagnose what would cause `MixerConnection.Channels.GetChannel` to just hang an application? There's no exception thrown, no type errors, nothing - it just hangs indefinitely.

I've tried the following and both seem to hang:
```c#
ChannelDetailsModel channelDetails = await mixerConnection.Channels.GetChannelDetails(channel);
this.Logger.Info("Channel Details: " + channelDetails);

ExpandedChannelModel channelModel = await mixerConnection.Channels.GetChannel(channel);
this.Logger.Info("Channel Model: " + channelModel);
```

```c#
ExpandedChannelModel uptimeChannel = await mixerConnection.Channels.GetChannel(channel);
if (uptimeChannel.online)
{
	this.Logger.Info("Channel: " + uptimeChannel);
}
else
{
	return channel + " is not currently streaming!";
}
```

**Comment by SaviorXTanren** [comment]
I just ran a few tests of the API and didn't see any issues. The channel endpoint specifically shouldn't hang indefinitely, HTTP calls will timeout after a minute or so normally. It's possible Mixer was experiencing some issues at the time.

**Comment by xlxAciDxlx** [comment]
That's really weird, I can still reproduce it. If I pause the debugger while the application is hung, it seems to be stuck on `AwaitingForActivation` status. Any clue what that means? Other places I use this method work perfectly fine, it just seems to be in this one method it hangs.

**Comment by SaviorXTanren** [comment]
AwaitingOnActivations is most likely a .NET framework method, has nothing to do with us. Download the code from GitHub and run one of the sample apps (They all make a call to GetChannel(). If it doesn't work, then there's something going on with your computer. If it does work, then it's something with your code.

I'd need to see the entire code sample and how it's being called to know more about what's going on. Are you wrapping it up in Task.Run()? Is there an exception being thrown that you're not catching? Lots of things that could be causing the issue you're seeing.

**Comment by xlxAciDxlx** [comment]
Sorry, I wasn't trying to imply it's anything wrong on your end - I'm sure it's not. Weirdly enough, if I run it in a wrapped `Task.Run` it works fine. However, if I use `await` it seems to hang the application.

Also, assuming it is an exception problem, wouldn't it still get thrown and the application would just error out if I click Ok? I can leave the application running and nothing ever pops up. I'll try wrapping it in a try/catch and see if somehow it's just one-offing in a weird way.

The really odd thing is the way the method gets called and responds are exactly the same as other methods, and they all work fine (obviously aside from in this one instance). I'll double and triple check variables and everything like that to make sure I'm not making some kind of blatantly obvious mistake and get back to you.

**Comment by SaviorXTanren** [comment]
Oh, you're good. I wasn't implying that you were implying that. Just was trying to walk you through some ways to validate the issue. :)

So, trying to explain the ins-and-outs of how async works is a little difficult. There's a lot of gotchas that can occur. What might be easier is actually seeing the code you are trying this in. Can you paste the method in here that's running and explain whats happening that causes the method to get called? Is it inside if something like a Button Click method?

**Comment by xlxAciDxlx** [comment]
This is the whole method:
```c#
public async Task<String> GetUptime(String service, dynamic channel = null)
{
	if (channel == null)
	{
		this.Logger.Error("No channel specified, skipping uptime check..");
		return "";
	}

	if (service == "Mixer")
	{
		MixerService mixerService = (MixerService)Bot.Instance.GetService("Mixer");
		MixerConnection mixerConnection = (MixerConnection)mixerService.GetConnection(0);
		if (mixerConnection == null)
		{
			this.Logger.Error("No Mixer connection available, skipping uptime check..");
			return "";
		}

		ExpandedChannelModel uptimeChannel = await Task.Run(() => mixerConnection.Channels.GetChannel(channel)).Result;
		if (uptimeChannel.online)
		{
			this.Logger.Info("Channel: " + uptimeChannel);
		}

		return "";
	}
	else
	{
		return this.GetNotImplementedMessage();
	}
}
```

That method gets called by my command processor which creates an instance of the command class (if it's a command that requires logic and has an internal class, anyway) and then calls `GetResponse` (this method) which then calls to `SendResponse(service,channel,response)` to send the response to whatever service was specified (Mixer, Discord, etc)

**Comment by SaviorXTanren** [comment]
The way you handle tasks & asyn is....interesting. Have you worked with async before? Not meant to be an insult, you just have a lot of extra logic that wrapped around calling an async method that is most certainly going to sprout up issues. The following code should:

`ExpandedChannelModel uptimeChannel = await Task.Run(() => mixerConnection.Channels.GetChannel(channel)).Result;`

Should really just be this:

`ExpandedChannelModel uptimeChannel = await mixerConnection.Channels.GetChanel(channel);`

I cant really fit a full and comprehensive explanation for the way Tasks & async work, but here are some rule of thumb (These are not exhaustive and there are situations where these are not true):

- Async allows you to not hang your main process/UI by putting all method calls that use "await" into a background thread, rather than using the UI thread that it might have been called from.
- If you are already inside an async method (It has async in the method header) and you want to call another async method, just stick an "await" in front of the method call
- If you are calling a method that is async and you DO NOT want to await it, simply add a ".Wait()" at the end if it DOES NOT return a result or a ".Result" if it does.
- Task.Run() should only be used if you want to run a set of code in a separate thread from the one you are currently in. For example, you want to have a process that pulls the latest info of the user's channel every 10 seconds, regardless of whatever is going on in the UI

If you want to learn more about tasks & async, you should check out this article: https://docs.microsoft.com/en-us/dotnet/csharp/async

**Comment by xlxAciDxlx** [comment]
> Have you worked with async before?

Not in this capacity, no. I'm trying to learn from both looking at how you do things and tutorials online.

> you just have a lot of extra logic that wrapped around calling an async method that is most certainly going to sprout up issues.

I should clarify, it's done that way to allow for the expansion amongst other libraries (i.e Discord, Twitch, etc). I know if I was only working with Mixer that could very much be simplified to just my bot > class > method.

> Should really just be...

I've tried that as well, both lock up. Uncommenting just the way I currently have it allows everything else to work (obviously aside from it not having an actual response)

> If you want to learn more about tasks & async, you should check out this article

Thank you, I'll definitely check that out!

**Comment by SaviorXTanren** [comment]
If you would like, I'd be happy to sit down with you and talk about this more, as I think this is something with your code that's causing issues. I can also help you with how to build out some logic to work with both sync & async methods the way you want to.

Feel free to add me on Discord: SaviorXTanren#5641

**Comment by xlxAciDxlx** [comment]
Thank you, I was actually going to ask if there was a better way to contact you. Haha I'll send you a message in a bit.
