### ISSUE TITLE
Chatters List API deprecation

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#49]
It looks like the V1 of the Chatters List API is being deprecated on December 12, 2018.   It appears they are removing a couple endpoints and changing the Chat User model to remove some fields.  

Deprecation reference: https://dev.mixer.com/content/blog/chatlistdeprecations 
New API reference: https://dev.mixer.com/reference/chat/chatchatterslist

**Comment by SaviorXTanren** [comment]
Because Mixer isn't planning on doing a clean cut over for their versions, we're gonna need to straddle the version fence for a while. Current plan is to do a nested class structure & re-purpose existing methods when possible.

So for example, we'll have a private ChatsV2Service class that will live inside the ChatsService class. This class will implement the V2 methods & the regular ChatsService class will simply act as a pass-through for any V2 methods. This will allow us to gradually migrate new methods over & attempt to minimize as much change for users of the API as possible.

Currently we're blocked on finishing this as the API doesn't appear to be working; all my calls are coming back with 404's. So once we have that resolved, we'll commit the change & roll out an update.
