### ISSUE TITLE
Custom Interactive Controls

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#55]
With Mixer it is possible to create custom interactive controls.  Currently this library will only work with the default Mixer interactive controls and it appears there is no simple way to bring in custom controls without making a custom version of this library.  Any thoughts on how to support custom interactive controls?

**Comment by SaviorXTanren** [comment]
So, let's separate out custom controls from custom MixPlay a bit. Custom MixPlay is fully supported, as it's no different than regular MixPlay. If your controls that you're making are based off of the standard MixPlay controls, they'll also continue to work fine. If you're designing your own control type, you'll need pull the repo and add that custom logic into the following class:

https://github.com/SaviorXTanren/mixer-client-csharp/blob/master/Mixer.Base/Model/Interactive/InteractiveControlCollectionModel.cs

Since Mixer returns an unstructured JSON array of controls, we won't know what types each of them are to correct unserialize & reserialize them. So you'll need to add in those times into there.

**Comment by mphacker** [comment]
Sounds good.  That is what I am doing.  Just wanted to make sure I wasn’t heading down a path different than what you were thinking.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
