### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#58]
It appears that rate limits are not being checked or managed for any of the calls.  This can cause issues in methods such as CheckIfFollows in the ChannelService object where it loops through groupings of 25 users to call the channels/{channelId}/follow endpoint.   If there are enough users provided in the array then this method could easily exceed the channel-read bucket limit.  This means that the data returned is not reliable.

For example, if a bot is trying to verify the follower status for a user or group of users the data returned might be incorrect if the call exceeded the Mixer rate limit.

It would be a big undertaking, but it would probably make sense to track rate limit info for each bucket type and then throttle REST calls so that the data for all method calls are more reliable.

**Comment by SaviorXTanren** [comment]
Realistically speaking, an API should never undertake that work, as that then is taking over business logic from the user of the API. Throttle limits can change as time goes on, so I don't want to get into the business of maintaining those. Additionally, you have multiple endpoints that can share the same throttle bucket, as the analytics ones. So if you're making multiple calls against these, you'll end up running into essentially a throttle race between them.

That said, we can look into exposing an event that is triggered when a rate limit is hit for any service. However, I can't guarantee that the response included will indicate which bucket the rate limit was hit on, but I'll see if I can find a way to indicate that.

**Comment by mphacker** [comment]
100% agree that the business logic needs to properly respond to limits and this library shouldn't do it automatically.  I don't think we need to have the buckets managed by this library, just someway to easily know that a rate limit is being hit.   I know that the HTTP response headers include x-rate-limit, x-ratelimit-remaining, and x-ratelimit-reset.  I could see that data being very useful to have accessible to the business logic.     Not sure how this could easily be added without some pretty major breaking changes to the library,  but it might be worth it to support the additional returned data.

**Comment by SaviorXTanren** [comment]
Without returning every result set as some sort of a wrapper result that contains that data (gets a little messy and overbearing when not needed), there's not a good way to pass that data along. For a first step at least, I can look into setting up a rate limit exception that would be thrown from a request if we detect a 429 that would include any partial result we got so far, plus whatever other relevant info we can scrape.

**Comment by SaviorXTanren** [comment]
So, I added in two things:

- A new exception will be thrown when a rate limit has been reached and will let you know which bucket it is
- An event has been added to all services that will be triggered when any updates for a rate limit have been received

However, this isn't a perfect solution due to the way Mixer has designed their headers for rate limiting. Below you'll find an example of what I mean:

![image](https://user-images.githubusercontent.com/752903/61693713-e4a43b00-ace4-11e9-990c-1030fe333049.png)

The headers on the left are what you get when making a normal request again a rate-limited endpoint while the headers on the right are what you get when you hit said rate limit. Notice how the left doesn't tell you which bucket you're hitting, while the right doesn't tell you when the rate limit resets. Also both of those missing values are stomped into the same header name, which means Mixer will need to implement a breaking change to their header structure to support knowing both which bucket is being called against and when the rate limit will reset in both scenarios.

**Comment by SaviorXTanren** [comment]
The check in above adds in the wrapping of partial data to the exception, so all of the paged data will now return whatever results we had gathered so far when the rate limit request occurred (though you'll need to type-cast the data out from it). At present, I think this is the best that can be done right now until Mixer makes changes to their rate limiting info in the headers.

**Comment by mphacker** [comment]
This was only pushed into the v1changes branch, correct?   Is the V1 branch pretty stable from a Mixer perspective to be used instead of the main branch version?   I know there will be breaking changes to move to V1 due to the moving of OAUTH into a new shared assembly.

**Comment by SaviorXTanren** [comment]
v1 is stable, there will just be a fair amount of breaking changes. The main purpose of the v1 updates are the following:

- Adding libraries for Twitch & YouTube that follow similar standards to the Mixer library thus far
- Adding full code documentation to the Mixer library
- Centralizing lots of shared code between the libraries
