### ISSUE TITLE
Crashes after logging in

### ISSUE THREAD

**Issue by takoz53** [SaviorXTanren/mixer-client-csharp#64]
`connection = MixerConnection.ConnectViaLocalhostOAuthBrowser(clientID, scopes).Result;`

Opens up the browser, logs in.
After login though, it just crashes. It goes to my Main function
`static void Main() => MainAsync().GetAwaiter().GetResult();` with the error:

> System.AggregateException: 'One or more errors occurred.'
> Inner Exception
> RestServiceRequestException: Bad Request

The setup is as follows:
Website: google.com
hosts: localhost
No secret key.

**Comment by SaviorXTanren** [comment]
What is the actual contents of the RestServiceRequestException? I would need to see what the values are for the Request, StatusCode, Reason, & Content fields on it.

**Comment by takoz53** [comment]
I'm not sure. I can't somehow check it as when I leave the step to see results, it just jumps to my Main. Is there a way to provide this somehow? If you want, it might be easier to communicate via discord? たここ#1196

**Comment by SaviorXTanren** [comment]
Just throw a try-catch around that for type RestServiceRequestException and then you can explore the contents of the exception while debugging your application.

**Comment by takoz53** [comment]
Content: "{\"error\":\"invalid_client\",\"error_description\":\"OAuth client secret invalid.\"}"
StatusCode: System.Net.HttpStatusCode.BadRequest
Request: "https://mixer.com/api/v1/oauth/token"
Reason: "Bad Request"

I'm not suer how my client secret is invalid when your ConnectViaLocalhostOAuthBrowser function only wants "clientID" and scopes.

**Comment by SaviorXTanren** [comment]
The ConnectViaLocalhostOAuthBrowser method has multiple overloads, you're just using one that doesn't specify a client secret. However, because you're getting that error, you must have clicked the option on mixer.com/lab to generate a client secret for your application. Because of this, you are now required to always specify a client secret. So update your code to specify your client secret or build a new application without selecting the option to generate a client secret.

**Comment by takoz53** [comment]
I don't have a client secret selected on /lab/.
